### ISSUE TITLE
Missing master path for "To-Do"

### ISSUE THREAD

**Issue by vdbhb59** [k3b/F-Droid-Universal-Catalog#5]
The 'k3b/F-Droid-Universal-Catalog' repository doesn't contain the 'k3b/F-Droid-Universal-Catalog/wiki' path in 'master'.
The readme to-do link is incorrect, and throws the above error, mate.

**Comment by k3b** [comment]
Fixed link form https://github.com/k3b/F-Droid-Universal-Catalog[README] to wiki home.  Thanks for reporting
